spring:
  application:
    name: api-center-backend
  # DataSource Config
  datasource:
    driver-class-name: # todo 改为自己的 MySQL 配置
    url: # todo 改为自己的 MySQL 配置
    username: # todo 改为自己的 MySQL 配置
    password: # todo 改为自己的 MySQL 配置
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: # todo 改为自己的 Redis 配置
    host: # todo 改为自己的 Redis 配置
    database: # todo 改为自己的 Redis 配置
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      # 需要在实体类的作为全局逻辑删除字段名的前面添加 @TableLogic 注解

apicenter:
  client:
    access-key: huaixv06
    secret-key: 123456

# 以下配置指定了应用的名称、使用的协议（Dubbo）、注册中心的类型（Nacos）和地址
dubbo:
  application:
    # 设置应用的名称
    name: dubbo-springboot-demo-provider
  # 指定使用 Dubbo 协议，且端口设置为 -1，表示随机分配可用端口
  protocol:
    name: dubbo
    port: 22221
  registry:
    # 配置注册中心为 Nacos，使用的地址是 nacos://localhost:8848
    id: nacos-registry
    address: nacos://localhost:8848


